[providers]
node = true
python = true

[build]
cmds = [
  "cd frontend && npm install && npm run build",
  "mkdir -p backend/staticfiles",
  "cp -r frontend/dist/* backend/staticfiles/",
  "pip install -r backend/requirements.txt"
]

[start]
cmd = "cd backend && gunicorn config.wsgi --bind 0.0.0.0:$PORT"
